In [10]:
import pandas as pd
import numpy as np

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
df=pd.read_csv("btissue.csv")
df.head()

,I0,PA500,HFS,DA,Area,A/DA,Max IP,DR,P,class
0,524.794072,0.187448,0.032114,228.800228,6843.598481,29.910803,60.204880,220.737212,556.828334,car
1,330.000000,0.226893,0.265290,121.154201,3163.239472,26.109202,69.717361,99.084964,400.225776,car
2,551.879287,0.232478,0.063530,264.804935,11888.391830,44.894903,77.793297,253.785300,656.769449,car
3,380.000000,0.240855,0.286234,137.640111,5402.171180,39.248524,88.758446,105.198568,493.701814,car
4,362.831266,0.200713,0.244346,124.912559,3290.462446,26.342127,69.389389,103.866552,424.796503,car

In [13]:
df.shape

(106, 10)

In [14]:
data_train,data_test=train_test_split(df,test_size=0.3,random_state=42)

In [15]:
data_train.shape

(74, 10)

In [16]:
len(data_test)

32

In [17]:
df1=pd.read_csv("auto_mpg.csv")
df1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [18]:
df1.shape

(398, 9)

In [19]:
from sklearn.model_selection import KFold

In [20]:
kf=KFold(n_splits=10,shuffle=True,random_state=42)

In [21]:
for fold,(train_index,test_index) in enumerate(kf.split(df1),1):
    print("Fold",fold)
    print("Train indices:",train_index)
    print("Test indices:",test_index,"\n")

Fold 1
Train indices: [  1   2   3   4   5   6   7   8  10  11  12  13  14  16  17  18  19  20
  21  22  23  24  25  26  27  28  29  30  31  32  34  35  36  37  38  39
  40  41  43  44  45  46  47  48  49  50  51  52  53  54  55  58  59  60
  61  62  63  64  65  66  67  68  69  70  71  73  74  75  76  78  79  80
  81  82  83  85  86  87  88  89  90  91  92  95  96  97  98  99 100 101
 102 103 105 106 107 108 109 110 111 112 115 117 118 119 120 121 122 123
 124 125 127 128 129 130 131 133 134 135 136 137 138 139 140 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 159 160 161 162 163
 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181
 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 199 200
 201 202 203 204 205 206 207 209 210 211 212 213 214 215 216 217 218 219
 220 221 223 224 225 226 227 228 230 231 232 233 235 236 237 239 240 241
 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259
 260 263 264 265 266 267 268 269 270 271 272 273 274 276 277 278 279 280
 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297 299
 300 301 302 303 304 305 306 307 308 309 310 311 313 314 315 316 317 318
 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335 336
 337 338 339 340 341 342 343 344 345 346 347 348 349 350 351 352 353 354
 355 356 357 358 359 360 361 362 363 364 365 366 367 368 369 371 372 374
 376 378 379 380 381 382 384 385 386 387 388 390 391 392 395 397]
Test indices: [  0   9  15  33  42  56  57  72  77  84  93  94 104 113 114 116 126 132
 141 158 198 208 222 229 234 238 261 262 275 298 312 370 373 375 377 383
 389 393 394 396]

Fold 2
Train indices: [  0   1   2   3   4   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  23  24  26  27  28  29  32  33  34  35  36  37  38  40  41
  42  43  44  47  48  49  50  51  52  53  54  56  57  58  59  60  61  62
  63  64  65  66  67  68  69  71  72  74  75  77  79  80  81  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 102 103 104
 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122
 123 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 141 142
 143 144 145 146 147 149 150 151 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 169 170 171 173 174 176 177 178 179 182 183 184 185
 186 187 188 189 190 191 192 193 194 195 197 198 199 200 201 202 203 204
 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222
 223 224 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241
 242 243 244 245 246 247 248 250 251 252 253 254 255 256 257 258 259 260
 261 262 263 264 265 266 267 268 269 270 271 273 274 275 276 277 278 279
 280 281 282 283 284 286 287 288 289 290 291 293 295 296 297 298 299 300
 301 302 303 304 305 306 308 309 310 311 312 313 314 315 316 317 319 320
 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335 336 338 339
 340 342 343 344 345 346 347 348 349 352 353 354 355 356 357 358 359 360
 361 362 363 364 365 366 368 369 370 371 372 373 374 375 376 377 378 379
 381 382 383 384 385 387 388 389 390 391 392 393 394 395 396 397]
Test indices: [  5  22  25  30  31  39  45  46  55  70  73  76  78  82 101 124 140 148
 152 168 172 175 180 181 196 225 249 272 285 292 294 307 318 337 341 350
 351 367 380 386]

Fold 3
Train indices: [  0   1   2   4   5   6   8   9  10  11  12  13  14  15  17  20  21  22
  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40
  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
  59  61  62  64  65  67  68  69  70  71  72  73  74  76  77  78  80  81
  82  83  84  85  86  87  88  89  91  92  93  94  95  96  97  98  99 100
 101 102 103 104 105 106 107 109 111 112 113 114 115 116 117 119 120 121
 122 123 124 125 126 127 128 129 130 132 133 134 135 136 138 139 140 141
 142 143 144 145 146 147 148 149 150 151 152 154 155 156 157 158 159 160
 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 178 179
 180 181 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 211 212 213 214 215 216 217
 219 220 221 222 223 224 225 226 227 228 229 230 232 233 234 235 236 237
 238 239 240 241 242 243 244 247 249 250 251 252 253 254 255 256 257 258
 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276
 278 279 281 282 283 285 286 287 288 289 290 292 293 294 295 297 298 299
 300 301 302 303 305 306 307 308 309 310 311 312 313 314 315 316 317 318
 319 320 321 322 324 325 326 327 328 329 330 331 332 333 335 336 337 338
 339 340 341 342 343 344 345 346 348 349 350 351 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 372 373 374 375 377 379 380
 381 382 383 385 386 387 388 389 390 391 392 393 394 395 396 397]
Test indices: [  3   7  16  18  19  60  63  66  75  79  90 108 110 118 131 137 153 177
 182 210 218 231 245 246 248 277 280 284 291 296 304 323 334 347 352 353
 371 376 378 384]

Fold 4
Train indices: [  0   1   2   3   4   5   7   8   9  11  12  13  14  15  16  18  19  20
  21  22  23  25  26  27  28  29  30  31  32  33  34  35  37  38  39  40
  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
  78  79  80  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
  97  98  99 100 101 102 104 105 106 107 108 110 112 113 114 115 116 117
 118 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136
 137 138 140 141 142 143 144 146 147 148 149 151 152 153 154 156 158 159
 160 161 162 163 164 165 166 167 168 169 170 171 172 174 175 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 193 196 197 198 199 200
 201 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 220
 221 222 223 224 225 226 228 229 230 231 232 233 234 235 236 238 240 241
 242 243 244 245 246 247 248 249 250 251 252 254 255 256 257 258 259 260
 261 262 263 264 265 266 267 268 269 270 271 272 273 275 276 277 278 279
 280 281 282 283 284 285 286 288 289 291 292 293 294 295 296 297 298 299
 300 301 302 303 304 305 306 307 308 309 311 312 313 314 315 316 317 318
 319 320 321 322 323 325 326 327 328 329 330 332 333 334 335 336 337 338
 339 340 341 342 343 344 346 347 348 350 351 352 353 354 356 357 359 360
 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 380
 381 382 383 384 385 386 387 388 389 390 391 393 394 395 396 397]
Test indices: [  6  10  17  24  36  59  81 103 109 111 119 139 145 150 155 157 173 176
 192 194 195 202 219 227 237 239 253 274 287 290 310 324 331 345 349 355
 358 361 379 392]

Fold 5
Train indices: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  24  25  26  27  28  29  30  31  32  33  34  35  36
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  70  71  72  73  74  75  76
  77  78  79  80  81  82  83  84  85  87  88  90  91  93  94  95  98  99
 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 124 126 127 128 129 130 131 132 133 134 135 136 137 138
 139 140 141 142 145 148 149 150 151 152 153 154 155 156 157 158 159 160
 161 162 164 166 168 169 170 171 172 173 174 175 176 177 178 179 180 181
 182 184 185 186 187 188 189 190 191 192 194 195 196 197 198 199 200 201
 202 204 205 206 207 208 209 210 212 213 214 215 216 217 218 219 220 221
 222 224 225 226 227 229 230 231 232 234 235 236 237 238 239 240 241 242
 243 244 245 246 247 248 249 251 252 253 254 255 256 257 259 260 261 262
 263 264 266 267 268 269 270 271 272 273 274 275 276 277 279 280 281 282
 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 300 303 304
 305 306 307 308 309 310 311 312 313 314 315 317 318 319 320 321 322 323
 324 325 326 328 329 330 331 332 333 334 337 338 339 340 341 342 343 344
 345 346 347 348 349 350 351 352 353 354 355 356 358 359 360 361 362 363
 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380 381
 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397]
Test indices: [ 23  37  67  68  69  86  89  92  96  97 122 123 125 143 144 146 147 163
 165 167 183 193 203 211 223 228 233 250 258 265 278 283 299 301 302 316
 327 335 336 357]

Fold 6
Train indices: [  0   1   3   4   5   6   7   8   9  10  12  13  14  15  16  17  18  19
  20  21  22  23  24  25  27  28  29  30  31  32  33  34  35  36  37  39
  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75
  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93
  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111
 113 114 116 118 119 121 122 123 124 125 126 128 130 131 132 133 134 135
 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 155
 156 157 158 159 160 161 162 163 165 166 167 168 169 170 171 172 173 174
 175 176 177 178 180 181 182 183 184 186 187 188 189 190 191 192 193 194
 195 196 198 200 201 202 203 205 206 207 208 210 211 212 213 214 215 216
 217 218 219 221 222 223 225 226 227 228 229 230 231 233 234 235 236 237
 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255
 256 257 258 259 260 261 262 263 264 265 267 269 270 271 272 273 274 275
 276 277 278 279 280 283 284 285 287 288 289 290 291 292 293 294 295 296
 297 298 299 300 301 302 303 304 306 307 308 309 310 311 312 313 315 316
 317 318 319 320 321 322 323 324 325 327 328 329 330 331 332 334 335 336
 337 338 339 340 341 343 344 345 347 348 349 350 351 352 353 354 355 356
 357 358 359 361 362 363 364 365 367 368 370 371 372 373 375 376 377 378
 379 380 381 383 384 386 387 388 389 391 392 393 394 395 396 397]
Test indices: [  2  11  26  38 112 115 117 120 127 129 136 154 164 179 185 197 199 204
 209 220 224 232 266 268 281 282 286 305 314 326 333 342 346 360 366 369
 374 382 385 390]

Fold 7
Train indices: [  0   1   2   3   5   6   7   8   9  10  11  13  14  15  16  17  18  19
  20  21  22  23  24  25  26  27  30  31  32  33  34  36  37  38  39  40
  42  43  45  46  47  48  49  50  52  53  54  55  56  57  58  59  60  61
  62  63  64  66  67  68  69  70  71  72  73  75  76  77  78  79  80  81
  82  84  86  87  88  89  90  91  92  93  94  96  97  98  99 100 101 102
 103 104 105 106 108 109 110 111 112 113 114 115 116 117 118 119 120 121
 122 123 124 125 126 127 128 129 130 131 132 134 135 136 137 138 139 140
 141 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 160
 161 162 163 164 165 166 167 168 169 171 172 173 174 175 176 177 179 180
 181 182 183 185 187 188 189 190 191 192 193 194 195 196 197 198 199 200
 201 202 203 204 205 207 208 209 210 211 212 213 214 215 216 217 218 219
 220 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238
 239 241 243 245 246 248 249 250 251 252 253 256 257 258 259 260 261 262
 263 264 265 266 267 268 269 270 272 273 274 275 276 277 278 279 280 281
 282 283 284 285 286 287 288 290 291 292 293 294 295 296 298 299 300 301
 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 318 319 322
 323 324 326 327 328 330 331 333 334 335 336 337 338 339 340 341 342 343
 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361
 362 363 364 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380
 381 382 383 384 385 386 388 389 390 391 392 393 394 395 396 397]
Test indices: [  4  12  28  29  35  41  44  51  65  74  83  85  95 107 133 142 159 170
 178 184 186 206 221 240 242 244 247 254 255 271 289 297 317 320 321 325
 329 332 365 387]

Fold 8
Train indices: [  0   1   2   3   4   5   6   7   9  10  11  12  13  15  16  17  18  19
  20  21  22  23  24  25  26  28  29  30  31  33  34  35  36  37  38  39
  41  42  43  44  45  46  48  49  50  51  52  53  54  55  56  57  58  59
  60  63  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80
  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  99
 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120 121 122 123 124 125 126 127 129 130 131 132 133 134 136 137 139
 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 157 158
 159 160 161 163 164 165 166 167 168 169 170 172 173 174 175 176 177 178
 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196
 197 198 199 201 202 203 204 205 206 208 209 210 211 214 217 218 219 220
 221 222 223 224 225 227 228 229 231 232 233 234 235 237 238 239 240 241
 242 243 244 245 246 247 248 249 250 251 252 253 254 255 257 258 259 261
 262 263 264 265 266 268 269 270 271 272 273 274 275 276 277 278 280 281
 282 283 284 285 286 287 289 290 291 292 293 294 295 296 297 298 299 301
 302 303 304 305 306 307 308 309 310 312 313 314 315 316 317 318 319 320
 321 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 339 341
 342 343 344 345 346 347 348 349 350 351 352 353 355 357 358 359 360 361
 362 363 365 366 367 369 370 371 372 373 374 375 376 377 378 379 380 381
 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397]
Test indices: [  8  14  27  32  40  47  61  62  64  98 100 128 135 138 156 162 171 200
 207 212 213 215 216 226 230 236 256 260 267 279 288 300 311 322 338 340
 354 356 364 368]

Fold 9
Train indices: [  0   2   3   4   5   6   7   8   9  10  11  12  14  15  16  17  18  19
  20  21  22  23  24  25  26  27  28  29  30  31  32  33  35  36  37  38
  39  40  41  42  44  45  46  47  48  50  51  54  55  56  57  58  59  60
  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78
  79  81  82  83  84  85  86  87  89  90  92  93  94  95  96  97  98  99
 100 101 102 103 104 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155
 156 157 158 159 160 162 163 164 165 167 168 169 170 171 172 173 174 175
 176 177 178 179 180 181 182 183 184 185 186 187 188 189 191 192 193 194
 195 196 197 198 199 200 202 203 204 206 207 208 209 210 211 212 213 214
 215 216 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 242 244 245 246 247 248 249 250 252 253 254
 255 256 257 258 260 261 262 265 266 267 268 270 271 272 274 275 276 277
 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 296
 297 298 299 300 301 302 304 305 307 308 310 311 312 313 314 316 317 318
 320 321 322 323 324 325 326 327 329 330 331 332 333 334 335 336 337 338
 340 341 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357
 358 359 360 361 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 382 383 384 385 386 387 389 390 392 393 394 395 396 397]
Test indices: [  1  13  34  43  49  52  53  80  88  91 105 134 161 166 190 201 205 217
 241 243 251 259 263 264 269 273 295 303 306 309 315 319 328 339 362 363
 381 388 391]

Fold 10
Train indices: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  49  51  52  53  55  56  57  59
  60  61  62  63  64  65  66  67  68  69  70  72  73  74  75  76  77  78
  79  80  81  82  83  84  85  86  88  89  90  91  92  93  94  95  96  97
  98 100 101 103 104 105 107 108 109 110 111 112 113 114 115 116 117 118
 119 120 122 123 124 125 126 127 128 129 131 132 133 134 135 136 137 138
 139 140 141 142 143 144 145 146 147 148 150 152 153 154 155 156 157 158
 159 161 162 163 164 165 166 167 168 170 171 172 173 175 176 177 178 179
 180 181 182 183 184 185 186 190 192 193 194 195 196 197 198 199 200 201
 202 203 204 205 206 207 208 209 210 211 212 213 215 216 217 218 219 220
 221 222 223 224 225 226 227 228 229 230 231 232 233 234 236 237 238 239
 240 241 242 243 244 245 246 247 248 249 250 251 253 254 255 256 258 259
 260 261 262 263 264 265 266 267 268 269 271 272 273 274 275 277 278 279
 280 281 282 283 284 285 286 287 288 289 290 291 292 294 295 296 297 298
 299 300 301 302 303 304 305 306 307 309 310 311 312 314 315 316 317 318
 319 320 321 322 323 324 325 326 327 328 329 331 332 333 334 335 336 337
 338 339 340 341 342 345 346 347 349 350 351 352 353 354 355 356 357 358
 360 361 362 363 364 365 366 367 368 369 370 371 373 374 375 376 377 378
 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 396]
Test indices: [ 20  21  48  50  54  58  71  87  99 102 106 121 130 149 151 160 169 174
 187 188 189 191 214 235 252 257 270 276 293 308 313 330 343 344 348 359
 372 395 397]

In [22]:
for data_train,data_test in kf.split(df1):
    df1_train=df1.iloc[data_train]
    df1_test=df1.iloc[data_test]

In [23]:
print("Train_index","\n",data_train)

Train_index
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  49  51  52  53  55  56  57  59
  60  61  62  63  64  65  66  67  68  69  70  72  73  74  75  76  77  78
  79  80  81  82  83  84  85  86  88  89  90  91  92  93  94  95  96  97
  98 100 101 103 104 105 107 108 109 110 111 112 113 114 115 116 117 118
 119 120 122 123 124 125 126 127 128 129 131 132 133 134 135 136 137 138
 139 140 141 142 143 144 145 146 147 148 150 152 153 154 155 156 157 158
 159 161 162 163 164 165 166 167 168 170 171 172 173 175 176 177 178 179
 180 181 182 183 184 185 186 190 192 193 194 195 196 197 198 199 200 201
 202 203 204 205 206 207 208 209 210 211 212 213 215 216 217 218 219 220
 221 222 223 224 225 226 227 228 229 230 231 232 233 234 236 237 238 239
 240 241 242 243 244 245 246 247 248 249 250 251 253 254 255 256 258 259
 260 261 262 263 264 265 266 267 268 269 271 272 273 274 275 277 278 279
 280 281 282 283 284 285 286 287 288 289 290 291 292 294 295 296 297 298
 299 300 301 302 303 304 305 306 307 309 310 311 312 314 315 316 317 318
 319 320 321 322 323 324 325 326 327 328 329 331 332 333 334 335 336 337
 338 339 340 341 342 345 346 347 349 350 351 352 353 354 355 356 357 358
 360 361 362 363 364 365 366 367 368 369 370 371 373 374 375 376 377 378
 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 396]

In [24]:
from sklearn.utils import resample

In [25]:
df.shape

(106, 10)

In [26]:
x=df.iloc[:,0:9]
x.shape

(106, 9)

In [27]:
x1=resample(x, n_samples=1000000,random_state=42)
x1.shape

(1000000, 9)

In [28]:
x1

,I0,PA500,HFS,DA,Area,A/DA,Max IP,DR,P
102,2600.000000,0.200538,0.208043,1063.441427,174480.476200,164.071543,418.687286,977.552367,2664.583623
51,274.993396,0.147131,0.137532,66.457943,1217.415651,18.318588,40.849678,52.421008,327.558639
92,1800.000000,0.091979,0.205251,362.863321,15021.553890,41.397278,217.833969,290.203640,1893.663712
14,485.668806,0.230209,0.134041,253.893699,8135.968359,32.044783,64.855446,245.470531,541.363975
71,1385.664721,0.092328,0.089361,202.480044,8785.028733,43.387134,143.092194,143.257780,1524.609204
...,...,...,...,...,...,...,...,...,...
4,362.831266,0.200713,0.244346,124.912559,3290.462446,26.342127,69.389389,103.866552,424.796503
104,2300.000000,0.045029,0.136834,185.446044,5086.292497,27.427344,178.691742,49.593290,2480.592151
50,310.000000,0.174707,0.165457,98.509961,2741.032044,27.824923,49.327862,85.270010,388.977808
58,250.000000,0.087092,0.092852,29.637510,180.761244,6.099070,26.142097,13.963263,280.122906
44,172.515797,0.127235,0.038397,37.543673,192.218148,5.119855,19.322081,32.189821,174.933770

In [29]:
tp=85
tn=9
fp=2
fn=4
tot=tp+tn+fp+fn
acc=(tp+tn)/tot
tpr=tp/(tp+fn)
fpr=fp/(fp+tn)
prec=tp/(tp+fp)
recall=tp/(tp+fn)
f1_score=(2*prec*recall)/(prec+recall)

In [30]:
print("accuracy= ",acc)
print("precision= ",prec)
print("recall= ",recall)
print("f1 score= ",f1_score)

accuracy=  0.94
precision=  0.9770114942528736
recall=  0.9550561797752809
f1 score=  0.9659090909090908